# -*- coding: utf-8 -*-
"""gamze süel - Gorev4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQ_JfhgE9G4SAqMNFM340uiOXwPAvvzT

https://raw.githubusercontent.com/zaferdemirkol/HerkesIcinYapayZeka/main/nba.csv
"""

import numpy as np
import pandas as pd

gmz=pd.read_csv("https://raw.githubusercontent.com/zaferdemirkol/HerkesIcinYapayZeka/main/nba.csv")
gmz

"""**1- Son 5 kaydı getirin**"""

print(gmz.tail())

"""**2- Sütunları getirin**"""

columns = gmz.columns
print(columns)

"""**3- Son 3 kaydın "Salary", "Team", "Name" alanlarını getirin**"""

gmz.loc[gmz.index[-3:], ["Salary", "Team", "Name"]]

"""**4- "Sport" isminde yeni bir sütun oluşturun ve bu sütunun bütün değerlerini "Basketball" yapın**"""

gmz["Sport"] = "Tennis"
gmz

"""**5- "league" isminde yeni bir sütun oluşturun ve bütün değerlerini "National Basketball Association" yapın**"""

gmz["league"] = "National Basketball Association"
gmz

"""**6- "Weight in Kilograms" isminde bir sütun oluşturun ve bu sütunun değerlerini "Weight" sütunlarını 0.453 ile çarpılmış olarak ekleyin**"""

gmz["Weight in Kilograms"] = gmz["Weight"] * 0.453
gmz

"""**7- NaN verilerini çıkarın**"""

gmz = gmz.dropna()
gmz

"""**8- NaN verilerini 0 ile doldurun**"""

filled = gmz.fillna(0)
filled

"""**9- "Name", "Age" ve "Salary" e göre sıralama yapın**"""

gmz.sort_values(by=["Name", "Age", "Salary"])